In [2]:
import torch

In [5]:
t = torch.randn(3, 3)
a = torch.randn(3,3)
m = torch.tensor([[1, 0, 1], [0, 1, 0], [1, 0, 1]], dtype=torch.bool)
print(t)
print(a)
print(a @ t)
print(a *t)

tensor([[-0.0610,  0.6165,  2.1326],
        [-0.4895,  0.1383,  1.7305],
        [-0.2719, -1.1306, -0.7722]])
tensor([[ 0.3373,  1.3573,  0.0451],
        [ 1.7349,  0.5740, -1.4266],
        [-2.0266, -0.4173, -1.8961]])
tensor([[-6.9725e-01,  3.4472e-01,  3.0334e+00],
        [ 1.0863e-03,  2.7618e+00,  5.7948e+00],
        [ 8.4357e-01,  8.3669e-01, -3.5797e+00]])
tensor([[-0.0206,  0.8367,  0.0962],
        [-0.8492,  0.0794, -2.4687],
        [ 0.5511,  0.4718,  1.4642]])


In [52]:

t = t * m.float()  # Apply mask to tensor t 
print(t)

tensor([[-0.2849, -0.0000,  0.4088],
        [-0.0000,  0.5333,  0.0000],
        [ 1.4673,  0.0000, -0.2008]])


In [22]:
print(torch.cat((t, a, m), dim=0))  # Concatenate tensors along the first dimension

tensor([[-0.2678, -0.0927,  0.2574],
        [ 0.6696, -1.6090,  0.0776],
        [-1.3099,  0.8091, -0.2462],
        [-1.3821,  0.4183, -0.1210],
        [-0.3753, -0.4889,  1.1836],
        [-0.0088, -1.8725, -0.4579],
        [ 1.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000]])
